export const forbiddenWords = [
  'abrangente',
  'robusto',
  'alavancar',
  'mergulhar',
  'tapeçaria',
  'reino',
  'essência',
  'vibrante',
  'dinâmico',
  'inovador',
  'ponta',
  'facilitar',
  'vitrine',
  'elevar',
  'embarcar',
  'jornada',
  'paixão',
  'empoderar',
  'desencadear',
  'revolucionar',
  'soluções',
  'entrega de valor',
  'mindset',
  'propósito',
  'ecossistema',
  'holistico',
  'centrado no usuário'
] as const;
