export const COPY = {
  pt: {
    nav: ['Trabalho', 'Stacks', 'Sobre', 'Contato'],
    status: 'Disponível · Q3 2026',
    eyebrow: 'Paloma Albieri · Brasil ⇄ Japan',
    heroTitle: ['De Ideias a', 'Interfaces', 'Funcionais.'],
    heroItalic: 'Interfaces',
    role: 'CEO & Creative Developer',
    taglineLeft: 'Lidero produtos onde estratégia encontra execução. Arquiteta digital, desenvolvedora de sistemas, e tradutora do abstrato.',
    taglineRight: 'Operação, código e direção criativa sob o mesmo teto — sem terceirizar a visão.',
    meta: [
      ['Base', 'BRA/ JPN'],
      ['Foco', 'Produto & Sistemas'],
      ['Idiomas', 'PT / JP'],
    ],
    //hoverHint: 'Hover para ação · Clique para sobre',
    timecode: 'Take 01 · 04:23:26',
    ctaVideo: 'Pressione · Sobre mim ↗',
    aboutLabel: '// Sobre',
    aboutTitle: 'Criatividade & Código',
    aboutBody: 'Olá, sou Paloma — Designer & Tech especializada em soluções digitais centradas no usuário. Atualmente resido em Hamamatsu, Japão.Atuei por 3 anos e meio no setor de manufatura, onde desenvolvi experiência em desenvolvimento de software, compreensão de processos produtivos e gestão de segurança. Hoje, foco no desenvolvimento de interfaces intuitivas que simplificam a experiência do usuário.Combino visão estratégica com execução de alto nível para entregar mais do que estética: soluções funcionais, seguras e orientadas à performance e usabilidade.',
    socials: [
        {label: 'WhatsApp', link: 'https://wa.me/817020122563'},
        {label: 'Instagram', link: 'https://instagram.com/paloma.albieri'},
        { label: 'Email', link: 'mailto:contato@palomaalbieri.com' },
        {label: 'Agendar call', link: 'https://calendar.app.google/rRpgFSAxLS5xpL1v9'},
    ],
    ticker: ['Product Systems', 'UX Engineering', 'Design Direction', 'Frontend Architecture', 'Strategic Operations', 'Fullstack Delivery'],
    bigName: 'Paloma Albieri',
    projectsLabel: 'Estudos de Caso · 2024 — 2026',
    projectsTitle: 'Sistemas que',
    projectsTitleItalic: 'performam',
    projectsTitleRest: '.',
    projectStackLabel: 'Stack',
    projectResultsLabel: 'Resultados',
    chapters: [
      {
        num: '01',
        kicker: 'O Criativo · Hospitality',
        title: 'Miaucafé —',
        titleItalic: 'imersão digital & UX',
        copy: 'Uma marca de nicho que precisava de uma presença online à altura da sua atmosfera acolhedora. Desenhei uma interface lúdica, intuitiva e centrada na reserva de horários e venda de produtos. Resultado: +45% em interações digitais nos primeiros três meses.',
        stacks: ['Figma', 'React', 'MUI', 'Supabase'],
        metrics: [['+45%', 'Interações digitais'], ['3mo', 'Time to live'], ['1.2s', 'Load estimado']],
        bgWord: 'café',
      },
      {
        num: '02',
        kicker: 'O Complexo · Enterprise',
        title: 'Construtora Connect —',
        titleItalic: 'transformação digital de RH',
        copy: 'Ajudei a equipe na criação de um dashboard bifocal para uma empreiteira: interface intuitiva para funcionários (folgas, holerites) e um painel potente para a gestão aprovar pedidos, monitorar documentos e garantir compliance técnico. Redução de 60% no tempo burocrático.',
        stacks: ['TypeScript', 'Next.js', 'Node.js', 'SQL', 'Vercel'],
        metrics: [['−60%', 'Tempo burocrático'], ['240+', 'Funcionários'], ['99.7%', 'Uptime']],
        bgWord: 'système',
      },
    ],
    stacksLabel: '// Central de Comando',
    stacksTitle: ['Ferramentas que ', 'confio', ' em produção.'],
    stacksBody: 'Uma grade calibrada — design, código e infraestrutura operando como um único organismo. Cada ferramenta selecionada para velocidade, manutenção e ambição.',
    contactLabel: '// Contato',
    contactTitle: ['Pronta para ', 'escalar', '? Vamos conversar.'],
    contactLead: 'Projetos de produto, consultorias estratégicas e colaborações criativas. Resposta em até 48h.',
    infoList: [
      ['E-mail', 'contato@palomaalbieri.com', 'mailto:contato@palomaalbieri.com'],
      ['Agendar call', 'Marcar Reunião', 'https://calendar.app.google/rRpgFSAxLS5xpL1v9'],
      ['Instagram', '@paloma.albieri', 'https://instagram.com/paloma.albieri'],
      ['WhatsApp', 'Enviar Mensagem', 'https://wa.me/817020122563'],
    ],
    form: {
      name: 'Seu nome',
      company: 'Empresa',
      email: 'E-mail',
      message: 'Sobre o projeto',
      messagePh: 'Conte o essencial — escopo, prazo, objetivo.',
      submit: 'Enviar',
    },
    footer: ['© 2026 Paloma Albieri', 'Made in Brazil & Japan', 'v. 3.1 · Live'],
  },
  jp: {
    nav: ['仕事', 'スタック', 'プロフィール', 'お問い合わせ'],
    status: '受付中 · 2026 Q3',
    eyebrow: 'パロマ・アルビエリ · ブラジル ⇄ 日本',
    heroTitle: ['アイデアから、', '機能する', 'インターフェースへ。'],
    heroItalic: '機能する',
    role: 'CEO & クリエイティブ・デベロッパー',
    taglineLeft: '戦略と実装が交わるプロダクトを率います。デジタル・アーキテクト、システム開発者、抽象の翻訳者。',
    taglineRight: 'オペレーション、コード、クリエイティブ・ディレクションを一つ屋根の下で — ビジョンは外注しません。',
    meta: [
      ['拠点', 'BRA/ JPN'],
      ['専門', 'プロダクト & システム'],
      ['言語', 'PT / JP'],
    ],
    timecode: 'Take 01 · 04:23:26',
    ctaVideo: 'クリック · プロフィール ↗',
    aboutLabel: '// プロフィール',
    aboutTitle: 'クリエイティブ・デベロッパー',
    aboutBody: 'はじめまして、Palomaと申します。Designer & Techとして、ユーザー中心のデジタルソリューションを専門としています。現在は日本の浜松市に在住しています。これまで製造業にて約3年半勤務し、ソフトウェア開発、製造プロセスの理解、安全管理の分野で経験を積んできました。現在は、ユーザー体験を重視した直感的なインターフェース設計に注力しています。戦略的な視点と高い実行力を活かし、美しさだけでなく、機能性・安全性・パフォーマンス・ユーザビリティを兼ね備えたソリューションを提供します。',
    socials: [
      {label: 'WhatsApp', link: 'https://wa.me/817020122563'},
      {label: 'Instagram', link: 'https://instagram.com/paloma.albieri'},
      {label: 'Email', link: 'mailto:contato@palomaalbieri.com'},
      {label: 'Agendar call', link: 'https://calendar.app.google/rRpgFSAxLS5xpL1v9'},
    ],
    ticker: ['プロダクト・システム', 'UXエンジニアリング', 'デザイン・ディレクション', 'フロントエンド設計', 'ストラテジック・オペレーション', 'フルスタック開発'],
    bigName: 'Paloma Albieri',
    projectsLabel: 'ケーススタディ · 2024 — 2026',
    projectsTitle: '成果を生む',
    projectsTitleItalic: 'システム',
    projectsTitleRest: '。',
    projectStackLabel: 'スタック',
    projectResultsLabel: '成果',
    chapters: [
      {
        num: '01',
        kicker: 'クリエイティブ · ホスピタリティ',
        title: 'Miaucafé —',
        titleItalic: 'デジタル没入 & UX',
        copy: '居心地の良い雰囲気にふさわしいオンライン・プレゼンスを必要としていたニッチなブランド。予約と商品販売に特化した、遊び心があり直感的なインターフェースを設計。最初の3ヶ月でデジタル・インタラクションが45%増加しました。',
        stacks: ['Figma', 'React', 'MUI', 'Supabase'],
        metrics: [['+45%', 'デジタル増加'], ['3ヶ月', '公開まで'], ['1.2秒', '推定読込']],
        bgWord: '猫',
      },
      {
        num: '02',
        kicker: '複雑系 · エンタープライズ',
        title: 'Construtora Connect —',
        titleItalic: '人事のデジタル変革',
        copy: '建設会社向けに、二つの視点を持つダッシュボードの開発をチームと共に担当しました。従業員向けには休暇申請や給与明細を確認できる直感的なインターフェースを提供し、管理側には申請承認、書類管理、技術コンプライアンスの確保を行える高機能なパネルを実装しました。その結果、事務作業にかかる時間を60％削減しました。',
        stacks: ['TypeScript', 'Next.js', 'Node.js', 'SQL', 'Vercel'],
        metrics: [['−60%', '事務時間'], ['240+', '従業員'], ['99.7%', '稼働率']],
        bgWord: 'système',
      },
    ],
    stacksLabel: '// コマンドセンター',
    stacksTitle: ['本番環境で', '信頼する', 'ツール。'],
    stacksBody: '設計・コード・インフラが一つの有機体として動くよう調整されたグリッド。速度、保守性、野心のために選ばれた道具たち。',
    contactLabel: '// お問い合わせ',
    contactTitle: ['スケール', 'の準備は', '？ お話ししましょう。'],
    contactLead: 'プロダクト案件、戦略アドバイザリー、クリエイティブなコラボレーション。48時間以内に返信します。',
    infoList: [
      ['メール', 'contato@palomaalbieri.com', 'mailto:contato@palomaalbieri.com'],
      ['ミーティング予約', 'ミーティングを予約', 'https://calendar.app.google/rRpgFSAxLS5xpL1v9'],
      ['Instagram', '@paloma.albieri', 'https://instagram.com/paloma.albieri'],
      ['WhatsApp', 'メッセージを送る', 'https://wa.me/817020122563'],
    ],
    form: {
      name: 'お名前',
      company: '会社',
      email: 'メール',
      message: 'プロジェクトについて',
      messagePh: '要点を教えてください — スコープ、期限、目的。',
      submit: '送信',
    },
    footer: ['© 2026 Paloma Albieri', 'Made in Brazil & Japan', 'v. 1.1 · Live'],
  },
  en: {
    nav: ['Work', 'Stacks', 'About', 'Contact'],
    status: 'Booking · Q3 2026',
    eyebrow: 'Paloma Albieri · Brasil ⇄ Japan',
    heroTitle: ['From Ideas', 'to Functional', 'Interfaces.'],
    heroItalic: 'Functional',
    role: 'CEO & Creative Developer',
    taglineLeft: 'I lead products where strategy meets execution. Digital architect, systems developer, translator of the abstract.',
    taglineRight: 'Operations, code and creative direction under one roof — without outsourcing the vision.',
    meta: [
      ['Base', 'BRA/ JPN'],
      ['Focus', 'Product & Systems'],
      ['Languages', 'PT / JP'],
    ],
    timecode: 'Take 01 · 04:23:26',
    ctaVideo: 'Press · About me ↗',
    aboutLabel: '// About',
    aboutTitle: 'Creativity ＆ Code',
    aboutBody: 'Hi, I’m Paloma — a Designer & Tech specialized in user-centered digital solutions. Currently based in Hamamatsu, Japan, I spent 3.5 years working in the manufacturing sector, where I gained experience in software development, production processes, and safety management(安全管理). Today, I focus on designing intuitive interfaces that simplify the user experience.I combine strategic thinking with high - level execution to deliver more than just aesthetics: functional, secure, and performance- driven solutions with a strong emphasis on usability.',
    socials: [
      {label: 'WhatsApp', link: 'https://wa.me/817020122563'},
      {label: 'Instagram', link: 'https://instagram.com/paloma.albieri'},
      {label: 'Email', link: 'mailto:contato@palomaalbieri.com'},
      {label: 'Schedule a call', link: 'https://calendar.app.google/rRpgFSAxLS5xpL1v9'},
    ],
    ticker: ['Product Systems', 'UX Engineering', 'Design Direction', 'Frontend Architecture', 'Strategic Operations', 'Fullstack Delivery'],
    bigName: 'Paloma Albieri',
    projectsLabel: 'Case Studies · 2024 — 2026',
    projectsTitle: 'Systems that',
    projectsTitleItalic: 'perform',
    projectsTitleRest: '.',
    projectStackLabel: 'Stack',
    projectResultsLabel: 'Results',
    chapters: [
      {
        num: '01',
        kicker: 'The Creative · Hospitality',
        title: 'Miaucafé —',
        titleItalic: 'digital immersion & UX',
        copy: 'A niche brand that needed an online presence worthy of its welcoming atmosphere. I designed a playful, intuitive interface focused on booking and product sales. Result: +45% digital interactions in the first three months.',
        stacks: ['Figma', 'React', 'MUI', 'Supabase'],
        metrics: [['+45%', 'Digital interactions'], ['3mo', 'Time to live'], ['1.2s', 'Estimated load']],
        bgWord: 'café',
      },
      {
        num: '02',
        kicker: 'The Complex · Enterprise',
        title: 'Construtora Connect —',
        titleItalic: 'HR digital transformation',
        copy: 'Collaborated with the team to develop a dual-perspective dashboard for a construction company: an intuitive interface for employees (time off requests, payslips) and a robust management panel for approving requests, monitoring documentation, and ensuring technical compliance. Resulted in a 60% reduction in administrative workload.',
        stacks: ['TypeScript', 'Next.js', 'Node.js', 'SQL', 'Vercel'],
        metrics: [['−60%', 'Bureaucracy time'], ['240+', 'Employees'], ['99.7%', 'Uptime']],
        bgWord: 'système',
      },
    ],
    stacksLabel: '// Command Center',
    stacksTitle: ['Tools I ', 'trust', ' in production.'],
    stacksBody: 'A calibrated grid — design, code and infrastructure operating as one organism. Each tool chosen for speed, maintenance and ambition.',
    contactLabel: '// Contact',
    contactTitle: ['Ready to', 'scale', '? Let\'s talk.'],
    contactLead: 'Product projects, strategic consulting and creative collaborations. Reply within 48h.',
    infoList: [
      ['E-mail', 'contato@palomaalbieri.com', 'mailto:contato@palomaalbieri.com'],
      ['Schedule a Call', 'Book a Meeting', 'https://calendar.app.google/rRpgFSAxLS5xpL1v9'],
      ['Instagram', '@paloma.albieri', 'https://instagram.com/paloma.albieri'],
      ['WhatsApp', 'Send a Message', 'https://wa.me/817020122563'],
    ],
    form: {
      name: 'Your name',
      company: 'Company',
      email: 'Email',
      message: 'About the project',
      messagePh: 'Tell me the essentials — scope, timeline, goal.',
      submit: 'Send',
    },
    footer: ['© 2026 Paloma Albieri', 'Made in Brazil & Japan', 'v. 1.7 · Live'],
  },
}
